export const SET_PROPERTY = "SET_PROPERTY";
export const TOGGLE_DRAWAL = "TOGGLE_DRAWAL";
export const DEL_PROPERTY = "DEL_PROPERTY";
export const EDIT_PROPERTY = "EDIT_PROPERTY";
export const UPDATE_PROPERTY = "UPDATE_PROPERTY";
export const UPDATE_SEARCH_TERM = "UPDATE_SEARCH_TERM";
export const UPDATE_GEOCODE = "UPDATE_GEOCODE";
